# Generated by Django 3.0.7 on 2020-07-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200703_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, default=0, max_length=400),
            preserve_default=False,
        ),
    ]
